version: '2'
services:
  app:
    build: .
    volumes:
      - .:/app:rw
    ports:
      - "8000:8000"
    depends_on:
      - postgis
    command: runserver 0.0.0.0:8000
  postgis:
    image: mdillon/postgis:9.5
    environment:
      POSTGRES_DB: django_us_markets
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
